AWSTemplateFormatVersion: 2010-09-09
Description: A sample template
Parameters:
 RegistryName:
  Type: String
  Default: registry
Resources:
  BFASchemaRegistry:
    Type: 'AWS::Glue::Registry'
    Properties: 
     Description: AWS Glue Schema Registry for BFA
     Name: !Ref RegistryName